from setuptools import setup

setup(name='coloredlids',
      version='0.1',
      description='Models of heat transfer, fluid flow and structural mechanics',
      url='https://github.com/dwweiss/coloredlids',
      keywords='theoretical, modelling, modeling, white box, gray box, grey box',
      author='Dietmar Wilhelm Weiss',
      license='GLGP 3.0',
      platforms=['Linux', 'Windows'],
      packages=['coloredlids', 
                'coloredlids.data', 
                'coloredlids.flow', 
                'coloredlids.geometry', 
                'coloredlids.heat',
                'coloredlids.mass',
                'coloredlids.matter', 
                'coloredlids.mech', 
                'coloredlids.numerics', 
                'coloredlids.tools'],
      package_dir={'coloredlids': 'src',        
                   'coloredlids.data': 'src/data',   
                   'coloredlids.flow': 'src/flow',   
                   'coloredlids.geometry': 'src/geometry',   
                   'coloredlids.heat': 'src/heat', 
                   'coloredlids.mass': 'src/mass',
                   'coloredlids.matter': 'src/matter', 
                   'coloredlids.mech': 'src/mech', 
                   'coloredlids.numerics': 'src/numerics',
                   'coloredlids.tools': 'src/tools'},
      include_package_data=True,
      install_requires=['numpy', 'matplotlib', 'pandas', 'scipy', 'grayboxes'],
      classifiers=['Programming Language :: Python :: 3',
                   'Topic :: Scientific/Engineering',
                   'License :: OSI Approved :: GLGP 3.0 License']
      )
